data_warehouse:
  outputs:
    dev:
      dbname: Test
      host: localhost
      pass: Lateralus0!
      port: 5434
      schema: dbt
      threads: 1
      type: postgres
      user: postgres
  target: dev
